# Generated by Django 2.1.4 on 2018-12-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('good_id', models.AutoField(primary_key=True, serialize=False)),
                ('good_name', models.CharField(max_length=200)),
                ('good_category', models.CharField(max_length=200)),
                ('good_description', models.TextField()),
            ],
        ),
    ]
