# Generated by Django 2.1.4 on 2018-12-11 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='good',
            name='good_category',
        ),
        migrations.AddField(
            model_name='good',
            name='good_cat_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='onlineshop.Category'),
            preserve_default=False,
        ),
    ]
